//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.28 at 04:14:44 PM EET 
//


package edu.marius.graph.entity;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="datePosted" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="educationRequirements" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="employmentType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="experienceRequirements" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hiringOrganization"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="image" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="industry" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="jobBenefits" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="jobLocation"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="address"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="addressLocality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="addressRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="occupationalCategory" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="qualifications" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *         &lt;element name="responsibilities" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="skills" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="workHours" type="{http://www.w3.org/2001/XMLSchema}byte"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datePosted",
    "description",
    "educationRequirements",
    "employmentType",
    "experienceRequirements",
    "hiringOrganization",
    "image",
    "industry",
    "jobBenefits",
    "jobLocation",
    "occupationalCategory",
    "qualifications",
    "responsibilities",
    "skills",
    "title",
    "url",
    "workHours"
})
@XmlRootElement(name = "jobPosting")
public class JobPosting {

    @XmlElement(required = true)
    protected String datePosted;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String educationRequirements;
    @XmlElement(required = true)
    protected String employmentType;
    @XmlElement(required = true)
    protected String experienceRequirements;
    @XmlElement(required = true)
    protected JobPosting.HiringOrganization hiringOrganization;
    @XmlElement(required = true)
    protected String image;
    @XmlElement(required = true)
    protected String industry;
    @XmlElement(required = true)
    protected String jobBenefits;
    @XmlElement(required = true)
    protected JobPosting.JobLocation jobLocation;
    @XmlElement(required = true)
    protected String occupationalCategory;
    protected byte qualifications;
    @XmlElement(required = true)
    protected String responsibilities;
    @XmlElement(required = true)
    protected String skills;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String url;
    protected byte workHours;
    @XmlAttribute(name = "context")
    @XmlSchemaType(name = "anyURI")
    protected String context;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the datePosted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatePosted() {
        return datePosted;
    }

    /**
     * Sets the value of the datePosted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatePosted(String value) {
        this.datePosted = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the educationRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducationRequirements() {
        return educationRequirements;
    }

    /**
     * Sets the value of the educationRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducationRequirements(String value) {
        this.educationRequirements = value;
    }

    /**
     * Gets the value of the employmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentType() {
        return employmentType;
    }

    /**
     * Sets the value of the employmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentType(String value) {
        this.employmentType = value;
    }

    /**
     * Gets the value of the experienceRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExperienceRequirements() {
        return experienceRequirements;
    }

    /**
     * Sets the value of the experienceRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExperienceRequirements(String value) {
        this.experienceRequirements = value;
    }

    /**
     * Gets the value of the hiringOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link JobPosting.HiringOrganization }
     *     
     */
    public JobPosting.HiringOrganization getHiringOrganization() {
        return hiringOrganization;
    }

    /**
     * Sets the value of the hiringOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPosting.HiringOrganization }
     *     
     */
    public void setHiringOrganization(JobPosting.HiringOrganization value) {
        this.hiringOrganization = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImage(String value) {
        this.image = value;
    }

    /**
     * Gets the value of the industry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * Sets the value of the industry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustry(String value) {
        this.industry = value;
    }

    /**
     * Gets the value of the jobBenefits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobBenefits() {
        return jobBenefits;
    }

    /**
     * Sets the value of the jobBenefits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobBenefits(String value) {
        this.jobBenefits = value;
    }

    /**
     * Gets the value of the jobLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JobPosting.JobLocation }
     *     
     */
    public JobPosting.JobLocation getJobLocation() {
        return jobLocation;
    }

    /**
     * Sets the value of the jobLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPosting.JobLocation }
     *     
     */
    public void setJobLocation(JobPosting.JobLocation value) {
        this.jobLocation = value;
    }

    /**
     * Gets the value of the occupationalCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupationalCategory() {
        return occupationalCategory;
    }

    /**
     * Sets the value of the occupationalCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupationalCategory(String value) {
        this.occupationalCategory = value;
    }

    /**
     * Gets the value of the qualifications property.
     * 
     */
    public byte getQualifications() {
        return qualifications;
    }

    /**
     * Sets the value of the qualifications property.
     * 
     */
    public void setQualifications(byte value) {
        this.qualifications = value;
    }

    /**
     * Gets the value of the responsibilities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsibilities() {
        return responsibilities;
    }

    /**
     * Sets the value of the responsibilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsibilities(String value) {
        this.responsibilities = value;
    }

    /**
     * Gets the value of the skills property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkills() {
        return skills;
    }

    /**
     * Sets the value of the skills property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkills(String value) {
        this.skills = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the workHours property.
     * 
     */
    public byte getWorkHours() {
        return workHours;
    }

    /**
     * Sets the value of the workHours property.
     * 
     */
    public void setWorkHours(byte value) {
        this.workHours = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "logo",
        "name",
        "url"
    })
    public static class HiringOrganization {

        @XmlElement(required = true)
        protected String logo;
        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String url;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the logo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLogo() {
            return logo;
        }

        /**
         * Sets the value of the logo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLogo(String value) {
            this.logo = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="address"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="addressLocality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="addressRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address"
    })
    public static class JobLocation {

        @XmlElement(required = true)
        protected JobPosting.JobLocation.Address address;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link JobPosting.JobLocation.Address }
         *     
         */
        public JobPosting.JobLocation.Address getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link JobPosting.JobLocation.Address }
         *     
         */
        public void setAddress(JobPosting.JobLocation.Address value) {
            this.address = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="addressLocality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="addressRegion" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressLocality",
            "addressRegion"
        })
        public static class Address {

            @XmlElement(required = true)
            protected String addressLocality;
            @XmlElement(required = true)
            protected String addressRegion;
            @XmlAttribute(name = "type")
            protected String type;

            /**
             * Gets the value of the addressLocality property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressLocality() {
                return addressLocality;
            }

            /**
             * Sets the value of the addressLocality property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressLocality(String value) {
                this.addressLocality = value;
            }

            /**
             * Gets the value of the addressRegion property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressRegion() {
                return addressRegion;
            }

            /**
             * Sets the value of the addressRegion property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressRegion(String value) {
                this.addressRegion = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }

}
