//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.20 at 07:30:01 PM EEST 
//


package edu.marius.graph.entity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.marius.graph.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cv_QNAME = new QName("", "Cv");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.marius.graph.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JobPosting }
     * 
     */
    public JobPosting createJobPosting() {
        return new JobPosting();
    }

    /**
     * Create an instance of {@link JobPosting.JobLocation }
     * 
     */
    public JobPosting.JobLocation createJobPostingJobLocation() {
        return new JobPosting.JobLocation();
    }

    /**
     * Create an instance of {@link JobPosting.HiringOrganization }
     * 
     */
    public JobPosting.HiringOrganization createJobPostingHiringOrganization() {
        return new JobPosting.HiringOrganization();
    }

    /**
     * Create an instance of {@link CvType }
     * 
     */
    public CvType createCvType() {
        return new CvType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link JobType }
     * 
     */
    public JobType createJobType() {
        return new JobType();
    }

    /**
     * Create an instance of {@link ExperienceType }
     * 
     */
    public ExperienceType createExperienceType() {
        return new ExperienceType();
    }

    /**
     * Create an instance of {@link EducationEntryType }
     * 
     */
    public EducationEntryType createEducationEntryType() {
        return new EducationEntryType();
    }

    /**
     * Create an instance of {@link EducationType }
     * 
     */
    public EducationType createEducationType() {
        return new EducationType();
    }

    /**
     * Create an instance of {@link LanguagesType }
     * 
     */
    public LanguagesType createLanguagesType() {
        return new LanguagesType();
    }

    /**
     * Create an instance of {@link CourseType }
     * 
     */
    public CourseType createCourseType() {
        return new CourseType();
    }

    /**
     * Create an instance of {@link CoursesType }
     * 
     */
    public CoursesType createCoursesType() {
        return new CoursesType();
    }

    /**
     * Create an instance of {@link SkillsType }
     * 
     */
    public SkillsType createSkillsType() {
        return new SkillsType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link ProjectsType }
     * 
     */
    public ProjectsType createProjectsType() {
        return new ProjectsType();
    }

    /**
     * Create an instance of {@link JobPosting.JobLocation.Address }
     * 
     */
    public JobPosting.JobLocation.Address createJobPostingJobLocationAddress() {
        return new JobPosting.JobLocation.Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CvType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cv")
    public JAXBElement<CvType> createCv(CvType value) {
        return new JAXBElement<CvType>(_Cv_QNAME, CvType.class, null, value);
    }

}
